export const HARNESS_WORKER_DISPATCH_QUEUE_PREFIX = 'harness_issue_dispatch'
export const HARNESS_WORKER_IDLE_STATUS = 'idle'
export const HARNESS_WORKER_BUSY_STATUS = 'busy'
export const HARNESS_WORKER_QUEUED_ISSUE_STATUS = 'queued'
export const HARNESS_WORKER_PLANNING_ISSUE_STATUS = 'planning'
export const HARNESS_WORKER_NEEDS_CLARIFICATION_ISSUE_STATUS = 'needs_clarification'
export const HARNESS_WORKER_PLAN_IN_REVIEW_ISSUE_STATUS = 'plan_in_review'
export const HARNESS_WORKER_IN_PROGRESS_ISSUE_STATUS = 'in_progress'
export const HARNESS_WORKER_NEEDS_HELP_ISSUE_STATUS = 'needs_help'
export const HARNESS_WORKER_PLANNING_NEEDS_HELP_ISSUE_STATUS = 'planning_needs_help'
export const HARNESS_WORKER_IN_REVIEW_ISSUE_STATUS = 'in_review'
export const HARNESS_WORKER_COMPLETED_ISSUE_STATUS = 'completed'
export const HARNESS_WORKER_CANCELED_ISSUE_STATUS = 'canceled'
export const DEFAULT_HARNESS_WORKER_HEARTBEAT_INTERVAL_MS = 10_000
export const DEFAULT_HARNESS_WORKER_POLL_INTERVAL_MS = 5_000
export const DEFAULT_HARNESS_WORKER_DISPATCH_VISIBILITY_TIMEOUT_SECONDS = 300

export const HARNESS_WORKER_CLAIMED_ISSUE_STATUSES = [
  HARNESS_WORKER_PLANNING_ISSUE_STATUS,
  HARNESS_WORKER_NEEDS_CLARIFICATION_ISSUE_STATUS,
  HARNESS_WORKER_PLAN_IN_REVIEW_ISSUE_STATUS,
  HARNESS_WORKER_IN_PROGRESS_ISSUE_STATUS,
  HARNESS_WORKER_NEEDS_HELP_ISSUE_STATUS,
  HARNESS_WORKER_PLANNING_NEEDS_HELP_ISSUE_STATUS,
  HARNESS_WORKER_IN_REVIEW_ISSUE_STATUS,
] as const

export const HARNESS_WORKER_TERMINAL_ISSUE_STATUSES = [
  HARNESS_WORKER_COMPLETED_ISSUE_STATUS,
  HARNESS_WORKER_CANCELED_ISSUE_STATUS,
] as const

export const getHarnessWorkerDispatchQueueName = (issueId: number): string =>
  `${HARNESS_WORKER_DISPATCH_QUEUE_PREFIX}_${issueId}`
